spring:
  datasource:
    url: jdbc:mysql://localhost:3306/costcontrolmanagement?useSSL=false
    username: root
    password: DEBUG
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  thymeleaf:
    cache: false
  http:
    encoding:
      charset: UTF-8

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml