spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CostControlManagement
    username: root
    password: Lianjc1246
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml